MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto;
using MagicVilla_Web.Models.VM;
using MagicVilla_Web.Services;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Reflection;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;
        private int _pageSize = 10;

        public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService, IMapper mapper,IConfiguration configuration)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;
            _mapper = mapper;
            _pageSize = _pageSize = configuration.GetValue<int>("PageSize:Value");
        }

        //public async Task<IActionResult> IndexVillaNumber()
        //{
        //    List<VillaNumberDTO> lstVilladto = new();

        //    var response = await _villaNumberService.GetAllAsync<APIResponse>();
        //    if (response != null && response.IsSuccess)
        //    {
        //        lstVilladto = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
        //    }

        //    return View(lstVilladto);
        //}

        public async Task<IActionResult> IndexVillaNumberPaged(int? pageNumber)
        {


            APIResponse response = await _villaNumberService.GetAllAsync<APIResponse>(_pageSize, pageNumber ?? 1);
            if (response != null && response.IsSuccess)
            {
                List<VillaNumberDTO> lst = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
                var queryable = lst.AsQueryable();

                var paginatedResult = await PaginatedList<VillaNumberDTO>.CreateAsync(queryable, pageNumber ?? 1, _pageSize);

                return View(paginatedResult);

            }


            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new();

            APIResponse response = await _villaService.GetAllAsync<APIResponse>();
//====================================================================================================
            //this is a hack
            //if(response!=null && response.IsSuccess && response.ErrorMessages.Count==0)
//====================================================================================================
            if(response!=null && response.IsSuccess)
            {
               var villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));

               villaNumberVM.VillaList = villaDTOs.Select(i => new SelectListItem { Text = i.Name, Value = i.Id.ToString() });

            }

            return View(villaNumberVM);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumberPaged));
                }
                else
                {
                    TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                        response.ErrorMessages[0] : "Error Encountered";
                }

            }

            APIResponse resp = await _villaService.GetAllAsync<APIResponse>();
            if(resp!=null && resp.IsSuccess)
            {
                var villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(resp.Result));
                model.VillaList = villaDTOs.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
            }


            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateVillaNumber(int villaNo)
        {
            VillaNumberUpdateVM villaNumberVM = new(); 
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo);

            if(response != null && response.IsSuccess)
            {
                VillaNumberDTO model  = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result)); 
                villaNumberVM.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model);
            }

            response = await _villaService.GetAllAsync<APIResponse>();
            if(response != null && response.IsSuccess)
            {
                var villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
                villaNumberVM.VillaList = villaDTOs.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

                return View(villaNumberVM);
            }
            else
            {
                TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                    response.ErrorMessages[0] : "Error Encountered";
            }

            return NotFound();

        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber);
                if(response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumberPaged));
                }
                else
                {
                    TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                        response.ErrorMessages[0] : "Error Encountered";
                }
            }


            APIResponse resp = await _villaService.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                var villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(resp.Result));
                model.VillaList = villaDTOs.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
            }


            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public async Task<IActionResult> DeleteVillaNumber(int villaNo)
        {
            VillaNumberDeleteVM villaNumberVM = new();
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo);

            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                villaNumberVM.VillaNumber = _mapper.Map<VillaNumberDTO>(model);
            }

            response = await _villaService.GetAllAsync<APIResponse>();
            if (response != null && response.IsSuccess)
            {
                var villaDTOs = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
                villaNumberVM.VillaList = villaDTOs.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

                return View(villaNumberVM);
            }

            return NotFound();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNumber.VillaNo);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumberPaged));
            }
            else
            {
                TempData["error"] = (response.ErrorMessages != null && response.ErrorMessages.Count > 0) ?
                    response.ErrorMessages[0] : "Error Encountered";
            }
            return View(model);
        }

    }
}

MagicVilla_Web/Views/VillaNumber/CreateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberCreateVM

<form asp-action="CreateVillaNumber">
    <br />
    
    <div class="container border p-4">
        <h1 class="text-primary text-center">Create VillaNumber</h1>
        <hr />
        <div class="row  pb-3 ms-2 me-5 w-60">
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5">
            </textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumberPaged" asp-controller="VillaNumber" class="btn btn-primary form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>

        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/DeleteVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberDeleteVM

<form asp-action="DeleteVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary text-center">Delete VillaNumber</h1>
        <hr />

        <input hidden asp-for="VillaNumber.VillaNo" />

        <div class="row  p-4 w-60">
           
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
                
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" disabled class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
               
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" disabled class="form-control" rows="5">
                </textarea>
                
            </div>
           
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumberPaged" asp-controller="VillaNumber" class="btn btn-primary form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control" />
            </div>

        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@model IEnumerable<MagicVilla_Web.Models.Dto.VillaNumberDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa Number List</h1>
        </div>

        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>&nbsp; Create New Villa Number</a>

        </div>

    </div>

    <table class="table">
        <thead>
            <tr class="border-bottom border-white">
                <th>
                   Villa Name
                </th>
                <th>
                    Villa Number
                </th>
                
                <th>

                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Villa.Name</td>
                    <td>@item.VillaNo</td>
                    <td>
                        <a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>

                    </td>
                </tr>
            }

        </tbody>
    </table>

</div>

MagicVilla_Web/Views/VillaNumber/IndexVillaNumberPaged.cshtml
@model PaginatedList<MagicVilla_Web.Models.Dto.VillaNumberDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa Number List</h1>
        </div>

        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i>&nbsp; Create New Villa Number</a>

        </div>

    </div>

    <table class="table">
        <thead>
            <tr class="border-bottom border-white">
                <th>
                    Villa Name
                </th>
                <th>
                    Villa Number
                </th>

                <th>

                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Villa.Name</td>
                    <td>@item.VillaNo</td>
                    <td>
                        <a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success"><i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger"><i class="bi bi-trash-fill"></i> Delete</a>

                    </td>
                </tr>
            }

        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            @if (Model.HasPreviousPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="IndexVillaNumberPaged" asp-route-pageNumber="@(Model.PageIndex - 1)">Previous</a>
                </li>
            }
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                    <a class="page-link" asp-action="IndexVillaNumberPaged" asp-route-pageNumber="@i">@i</a>
                </li>
            }
            @if (Model.HasNextPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="IndexVillaNumberPaged" asp-route-pageNumber="@(Model.PageIndex + 1)">Next</a>
                </li>
            }
        </ul>
    </nav>

</div>

MagicVilla_Web/Views/VillaNumber/UpdateVillaNumber.cshtml
@model MagicVilla_Web.Models.VM.VillaNumberUpdateVM

<form asp-action="UpdateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary text-center">Update VillaNumber</h1>
        <hr />
        <input hidden asp-for=VillaNumber.VillaNo />

        <div class="row">
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" disabled class="form-control" />
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.VillaID" class="control-label pt-2" style="font-size:20px"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaID" class="form-select" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaID" class="text-danger"></span>
            </div>


            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="VillaNumber.SpecialDetails" class="form-control" rows="5">
            </textarea>
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumberPaged" asp-controller="VillaNumber" class="btn btn-primary form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>

        </div>

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}